# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/wwu160/final-project-wayl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/wwu160/final-project-wayl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/wwu160/final-project-wayl/CMakeFiles /home/csmajs/wwu160/final-project-wayl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/wwu160/final-project-wayl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testInventory

# Build rule for target.
testInventory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testInventory
.PHONY : testInventory

# fast build rule for target.
testInventory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/build
.PHONY : testInventory/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Tests/test.o: Tests/test.cpp.o
.PHONY : Tests/test.o

# target to build an object file
Tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/Tests/test.cpp.o
.PHONY : Tests/test.cpp.o

Tests/test.i: Tests/test.cpp.i
.PHONY : Tests/test.i

# target to preprocess a source file
Tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/Tests/test.cpp.i
.PHONY : Tests/test.cpp.i

Tests/test.s: Tests/test.cpp.s
.PHONY : Tests/test.s

# target to generate assembly for a file
Tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/Tests/test.cpp.s
.PHONY : Tests/test.cpp.s

srcItemAndInventory/Inventory.o: srcItemAndInventory/Inventory.cpp.o
.PHONY : srcItemAndInventory/Inventory.o

# target to build an object file
srcItemAndInventory/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Inventory.cpp.o
.PHONY : srcItemAndInventory/Inventory.cpp.o

srcItemAndInventory/Inventory.i: srcItemAndInventory/Inventory.cpp.i
.PHONY : srcItemAndInventory/Inventory.i

# target to preprocess a source file
srcItemAndInventory/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Inventory.cpp.i
.PHONY : srcItemAndInventory/Inventory.cpp.i

srcItemAndInventory/Inventory.s: srcItemAndInventory/Inventory.cpp.s
.PHONY : srcItemAndInventory/Inventory.s

# target to generate assembly for a file
srcItemAndInventory/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Inventory.cpp.s
.PHONY : srcItemAndInventory/Inventory.cpp.s

srcItemAndInventory/Item.o: srcItemAndInventory/Item.cpp.o
.PHONY : srcItemAndInventory/Item.o

# target to build an object file
srcItemAndInventory/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Item.cpp.o
.PHONY : srcItemAndInventory/Item.cpp.o

srcItemAndInventory/Item.i: srcItemAndInventory/Item.cpp.i
.PHONY : srcItemAndInventory/Item.i

# target to preprocess a source file
srcItemAndInventory/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Item.cpp.i
.PHONY : srcItemAndInventory/Item.cpp.i

srcItemAndInventory/Item.s: srcItemAndInventory/Item.cpp.s
.PHONY : srcItemAndInventory/Item.s

# target to generate assembly for a file
srcItemAndInventory/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Item.cpp.s
.PHONY : srcItemAndInventory/Item.cpp.s

srcItemAndInventory/Pokeballs/GreatBall.o: srcItemAndInventory/Pokeballs/GreatBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.o

# target to build an object file
srcItemAndInventory/Pokeballs/GreatBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/GreatBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.cpp.o

srcItemAndInventory/Pokeballs/GreatBall.i: srcItemAndInventory/Pokeballs/GreatBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.i

# target to preprocess a source file
srcItemAndInventory/Pokeballs/GreatBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/GreatBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.cpp.i

srcItemAndInventory/Pokeballs/GreatBall.s: srcItemAndInventory/Pokeballs/GreatBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.s

# target to generate assembly for a file
srcItemAndInventory/Pokeballs/GreatBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/GreatBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/GreatBall.cpp.s

srcItemAndInventory/Pokeballs/Pokeball.o: srcItemAndInventory/Pokeballs/Pokeball.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.o

# target to build an object file
srcItemAndInventory/Pokeballs/Pokeball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/Pokeball.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.cpp.o

srcItemAndInventory/Pokeballs/Pokeball.i: srcItemAndInventory/Pokeballs/Pokeball.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.i

# target to preprocess a source file
srcItemAndInventory/Pokeballs/Pokeball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/Pokeball.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.cpp.i

srcItemAndInventory/Pokeballs/Pokeball.s: srcItemAndInventory/Pokeballs/Pokeball.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.s

# target to generate assembly for a file
srcItemAndInventory/Pokeballs/Pokeball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/Pokeball.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/Pokeball.cpp.s

srcItemAndInventory/Pokeballs/StandardBall.o: srcItemAndInventory/Pokeballs/StandardBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.o

# target to build an object file
srcItemAndInventory/Pokeballs/StandardBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/StandardBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.cpp.o

srcItemAndInventory/Pokeballs/StandardBall.i: srcItemAndInventory/Pokeballs/StandardBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.i

# target to preprocess a source file
srcItemAndInventory/Pokeballs/StandardBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/StandardBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.cpp.i

srcItemAndInventory/Pokeballs/StandardBall.s: srcItemAndInventory/Pokeballs/StandardBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.s

# target to generate assembly for a file
srcItemAndInventory/Pokeballs/StandardBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/StandardBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/StandardBall.cpp.s

srcItemAndInventory/Pokeballs/UltraBall.o: srcItemAndInventory/Pokeballs/UltraBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.o

# target to build an object file
srcItemAndInventory/Pokeballs/UltraBall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/UltraBall.cpp.o
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.cpp.o

srcItemAndInventory/Pokeballs/UltraBall.i: srcItemAndInventory/Pokeballs/UltraBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.i

# target to preprocess a source file
srcItemAndInventory/Pokeballs/UltraBall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/UltraBall.cpp.i
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.cpp.i

srcItemAndInventory/Pokeballs/UltraBall.s: srcItemAndInventory/Pokeballs/UltraBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.s

# target to generate assembly for a file
srcItemAndInventory/Pokeballs/UltraBall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Pokeballs/UltraBall.cpp.s
.PHONY : srcItemAndInventory/Pokeballs/UltraBall.cpp.s

srcItemAndInventory/Potions/HyperPotion.o: srcItemAndInventory/Potions/HyperPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/HyperPotion.o

# target to build an object file
srcItemAndInventory/Potions/HyperPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/HyperPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/HyperPotion.cpp.o

srcItemAndInventory/Potions/HyperPotion.i: srcItemAndInventory/Potions/HyperPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/HyperPotion.i

# target to preprocess a source file
srcItemAndInventory/Potions/HyperPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/HyperPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/HyperPotion.cpp.i

srcItemAndInventory/Potions/HyperPotion.s: srcItemAndInventory/Potions/HyperPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/HyperPotion.s

# target to generate assembly for a file
srcItemAndInventory/Potions/HyperPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/HyperPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/HyperPotion.cpp.s

srcItemAndInventory/Potions/Potion.o: srcItemAndInventory/Potions/Potion.cpp.o
.PHONY : srcItemAndInventory/Potions/Potion.o

# target to build an object file
srcItemAndInventory/Potions/Potion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/Potion.cpp.o
.PHONY : srcItemAndInventory/Potions/Potion.cpp.o

srcItemAndInventory/Potions/Potion.i: srcItemAndInventory/Potions/Potion.cpp.i
.PHONY : srcItemAndInventory/Potions/Potion.i

# target to preprocess a source file
srcItemAndInventory/Potions/Potion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/Potion.cpp.i
.PHONY : srcItemAndInventory/Potions/Potion.cpp.i

srcItemAndInventory/Potions/Potion.s: srcItemAndInventory/Potions/Potion.cpp.s
.PHONY : srcItemAndInventory/Potions/Potion.s

# target to generate assembly for a file
srcItemAndInventory/Potions/Potion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/Potion.cpp.s
.PHONY : srcItemAndInventory/Potions/Potion.cpp.s

srcItemAndInventory/Potions/StandardPotion.o: srcItemAndInventory/Potions/StandardPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/StandardPotion.o

# target to build an object file
srcItemAndInventory/Potions/StandardPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/StandardPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/StandardPotion.cpp.o

srcItemAndInventory/Potions/StandardPotion.i: srcItemAndInventory/Potions/StandardPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/StandardPotion.i

# target to preprocess a source file
srcItemAndInventory/Potions/StandardPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/StandardPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/StandardPotion.cpp.i

srcItemAndInventory/Potions/StandardPotion.s: srcItemAndInventory/Potions/StandardPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/StandardPotion.s

# target to generate assembly for a file
srcItemAndInventory/Potions/StandardPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/StandardPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/StandardPotion.cpp.s

srcItemAndInventory/Potions/SuperPotion.o: srcItemAndInventory/Potions/SuperPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/SuperPotion.o

# target to build an object file
srcItemAndInventory/Potions/SuperPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/SuperPotion.cpp.o
.PHONY : srcItemAndInventory/Potions/SuperPotion.cpp.o

srcItemAndInventory/Potions/SuperPotion.i: srcItemAndInventory/Potions/SuperPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/SuperPotion.i

# target to preprocess a source file
srcItemAndInventory/Potions/SuperPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/SuperPotion.cpp.i
.PHONY : srcItemAndInventory/Potions/SuperPotion.cpp.i

srcItemAndInventory/Potions/SuperPotion.s: srcItemAndInventory/Potions/SuperPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/SuperPotion.s

# target to generate assembly for a file
srcItemAndInventory/Potions/SuperPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Potions/SuperPotion.cpp.s
.PHONY : srcItemAndInventory/Potions/SuperPotion.cpp.s

srcItemAndInventory/Revives/MaxRevive.o: srcItemAndInventory/Revives/MaxRevive.cpp.o
.PHONY : srcItemAndInventory/Revives/MaxRevive.o

# target to build an object file
srcItemAndInventory/Revives/MaxRevive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/MaxRevive.cpp.o
.PHONY : srcItemAndInventory/Revives/MaxRevive.cpp.o

srcItemAndInventory/Revives/MaxRevive.i: srcItemAndInventory/Revives/MaxRevive.cpp.i
.PHONY : srcItemAndInventory/Revives/MaxRevive.i

# target to preprocess a source file
srcItemAndInventory/Revives/MaxRevive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/MaxRevive.cpp.i
.PHONY : srcItemAndInventory/Revives/MaxRevive.cpp.i

srcItemAndInventory/Revives/MaxRevive.s: srcItemAndInventory/Revives/MaxRevive.cpp.s
.PHONY : srcItemAndInventory/Revives/MaxRevive.s

# target to generate assembly for a file
srcItemAndInventory/Revives/MaxRevive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/MaxRevive.cpp.s
.PHONY : srcItemAndInventory/Revives/MaxRevive.cpp.s

srcItemAndInventory/Revives/Revive.o: srcItemAndInventory/Revives/Revive.cpp.o
.PHONY : srcItemAndInventory/Revives/Revive.o

# target to build an object file
srcItemAndInventory/Revives/Revive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/Revive.cpp.o
.PHONY : srcItemAndInventory/Revives/Revive.cpp.o

srcItemAndInventory/Revives/Revive.i: srcItemAndInventory/Revives/Revive.cpp.i
.PHONY : srcItemAndInventory/Revives/Revive.i

# target to preprocess a source file
srcItemAndInventory/Revives/Revive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/Revive.cpp.i
.PHONY : srcItemAndInventory/Revives/Revive.cpp.i

srcItemAndInventory/Revives/Revive.s: srcItemAndInventory/Revives/Revive.cpp.s
.PHONY : srcItemAndInventory/Revives/Revive.s

# target to generate assembly for a file
srcItemAndInventory/Revives/Revive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/Revive.cpp.s
.PHONY : srcItemAndInventory/Revives/Revive.cpp.s

srcItemAndInventory/Revives/StandardRevive.o: srcItemAndInventory/Revives/StandardRevive.cpp.o
.PHONY : srcItemAndInventory/Revives/StandardRevive.o

# target to build an object file
srcItemAndInventory/Revives/StandardRevive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/StandardRevive.cpp.o
.PHONY : srcItemAndInventory/Revives/StandardRevive.cpp.o

srcItemAndInventory/Revives/StandardRevive.i: srcItemAndInventory/Revives/StandardRevive.cpp.i
.PHONY : srcItemAndInventory/Revives/StandardRevive.i

# target to preprocess a source file
srcItemAndInventory/Revives/StandardRevive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/StandardRevive.cpp.i
.PHONY : srcItemAndInventory/Revives/StandardRevive.cpp.i

srcItemAndInventory/Revives/StandardRevive.s: srcItemAndInventory/Revives/StandardRevive.cpp.s
.PHONY : srcItemAndInventory/Revives/StandardRevive.s

# target to generate assembly for a file
srcItemAndInventory/Revives/StandardRevive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testInventory.dir/build.make CMakeFiles/testInventory.dir/srcItemAndInventory/Revives/StandardRevive.cpp.s
.PHONY : srcItemAndInventory/Revives/StandardRevive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... testInventory"
	@echo "... Tests/test.o"
	@echo "... Tests/test.i"
	@echo "... Tests/test.s"
	@echo "... srcItemAndInventory/Inventory.o"
	@echo "... srcItemAndInventory/Inventory.i"
	@echo "... srcItemAndInventory/Inventory.s"
	@echo "... srcItemAndInventory/Item.o"
	@echo "... srcItemAndInventory/Item.i"
	@echo "... srcItemAndInventory/Item.s"
	@echo "... srcItemAndInventory/Pokeballs/GreatBall.o"
	@echo "... srcItemAndInventory/Pokeballs/GreatBall.i"
	@echo "... srcItemAndInventory/Pokeballs/GreatBall.s"
	@echo "... srcItemAndInventory/Pokeballs/Pokeball.o"
	@echo "... srcItemAndInventory/Pokeballs/Pokeball.i"
	@echo "... srcItemAndInventory/Pokeballs/Pokeball.s"
	@echo "... srcItemAndInventory/Pokeballs/StandardBall.o"
	@echo "... srcItemAndInventory/Pokeballs/StandardBall.i"
	@echo "... srcItemAndInventory/Pokeballs/StandardBall.s"
	@echo "... srcItemAndInventory/Pokeballs/UltraBall.o"
	@echo "... srcItemAndInventory/Pokeballs/UltraBall.i"
	@echo "... srcItemAndInventory/Pokeballs/UltraBall.s"
	@echo "... srcItemAndInventory/Potions/HyperPotion.o"
	@echo "... srcItemAndInventory/Potions/HyperPotion.i"
	@echo "... srcItemAndInventory/Potions/HyperPotion.s"
	@echo "... srcItemAndInventory/Potions/Potion.o"
	@echo "... srcItemAndInventory/Potions/Potion.i"
	@echo "... srcItemAndInventory/Potions/Potion.s"
	@echo "... srcItemAndInventory/Potions/StandardPotion.o"
	@echo "... srcItemAndInventory/Potions/StandardPotion.i"
	@echo "... srcItemAndInventory/Potions/StandardPotion.s"
	@echo "... srcItemAndInventory/Potions/SuperPotion.o"
	@echo "... srcItemAndInventory/Potions/SuperPotion.i"
	@echo "... srcItemAndInventory/Potions/SuperPotion.s"
	@echo "... srcItemAndInventory/Revives/MaxRevive.o"
	@echo "... srcItemAndInventory/Revives/MaxRevive.i"
	@echo "... srcItemAndInventory/Revives/MaxRevive.s"
	@echo "... srcItemAndInventory/Revives/Revive.o"
	@echo "... srcItemAndInventory/Revives/Revive.i"
	@echo "... srcItemAndInventory/Revives/Revive.s"
	@echo "... srcItemAndInventory/Revives/StandardRevive.o"
	@echo "... srcItemAndInventory/Revives/StandardRevive.i"
	@echo "... srcItemAndInventory/Revives/StandardRevive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

